# Generated by Django 5.1.1 on 2024-10-03 09:05

import django.core.validators
import django.db.models.deletion
import helps.abstract.abstractclass
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0008_alter_ordersummary_deliveryzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transectionexpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transectionexpense_expense', to='account.expense')),
                ('ordersummary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transectionexpense_ordersummary', to='order.ordersummary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transectionincome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transectionincome_income', to='account.income')),
                ('ordersummary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transectionincome_ordersummary', to='order.ordersummary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
