# Generated by Django 5.1.1 on 2024-10-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_transectionexpense_transectionincome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transectionexpense',
        ),
    ]
