# Generated by Django 5.1.1 on 2024-10-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_transectionexpense'),
        ('order', '0011_alter_ordersummary_total_profit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transectionincome',
            new_name='Transection',
        ),
    ]
