# Generated by Django 5.1.1 on 2024-10-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transection_expense_alter_transection_income'),
        ('order', '0011_alter_ordersummary_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transection_expense', to='account.expense'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transection_income', to='account.income'),
        ),
        migrations.AlterField(
            model_name='transection',
            name='ordersummary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transection_ordersummary', to='order.ordersummary'),
        ),
    ]
