# Generated by Django 5.1.1 on 2024-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.CharField(blank=True, max_length=14, null=True, unique=True)),
            ],
        ),
    ]
