# Generated by Django 5.1.1 on 2024-10-06 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_by_product_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quntity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
