# Generated by Django 5.1.1 on 2024-11-07 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_quntity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quntity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
