# Generated by Django 5.1.1 on 2024-11-27 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_quntity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('product', 'product'), ('gift-box', 'gift-box'), ('general-box', 'general-box')], default='product', max_length=25),
        ),
    ]
