# Generated by Django 5.1.1 on 2024-12-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_capacity_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('product', 'product'), ('gift-box', 'gift-box'), ('general-box', 'general-box'), ('combo', 'combo'), ('external', 'external')], default='product', max_length=25),
        ),
    ]
