# Generated by Django 5.1.1 on 2024-10-21 11:20

import helps.abstract.abstractclass
import om_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=om_settings.models.uploadcompanylogo)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vat_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('business_identification_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bsti_registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('iso_certification_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('website_url', models.URLField(blank=True, null=True, unique=True)),
                ('facebook_url', models.URLField(blank=True, null=True, unique=True)),
                ('instagram_url', models.URLField(blank=True, null=True, unique=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True, unique=True)),
                ('tiktok_url', models.URLField(blank=True, null=True, unique=True)),
                ('x_url', models.URLField(blank=True, null=True, unique=True)),
                ('youtube_url', models.URLField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
