# Generated by Django 5.1.1 on 2024-10-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_permission_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
    ]
