# Generated by Django 5.1.1 on 2024-10-31 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_permissioncategory_role_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='user.permissioncategory'),
        ),
    ]
