# Generated by Django 5.1.1 on 2024-10-31 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_permission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user.permissioncategory'),
        ),
    ]
