# Generated by Django 5.1.1 on 2024-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Customer', 'Customer')], default=None, max_length=25, null=True),
        ),
    ]
