# Generated by Django 5.1.1 on 2024-12-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissioncategory',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
