# Generated by Django 5.1.1 on 2024-09-25 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordersummary_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='grand_total',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
