# Generated by Django 5.1.1 on 2024-09-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordersummary_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='payment_mode',
        ),
    ]
