# Generated by Django 5.1.1 on 2024-09-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordersummary_payment_mode'),
        ('zone', '0002_rename_zone_deliveryzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='deliveryzone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersummary_deliveryzone', to='zone.deliveryzone'),
        ),
    ]
