# Generated by Django 5.1.1 on 2024-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_ordersummary_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial Received', 'Partial Received'), ('Received', 'Received')], default='Pending', max_length=25),
        ),
    ]
