# Generated by Django 5.1.1 on 2024-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_ordersummary_created_by_ordersummary_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='total_profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
