# Generated by Django 5.1.1 on 2024-11-13 07:43

import helps.abstract.abstractclass
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordersummary_total_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storeorderid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_order_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
