# Generated by Django 5.1.1 on 2024-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_ordersummary_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
    ]
