# Generated by Django 5.1.1 on 2024-11-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_ordersummary_is_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='combo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
