# Generated by Django 5.1.1 on 2024-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordersummary_combo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='combo_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
