# Generated by Django 5.1.1 on 2024-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_ordersummary_combo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='combo_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
