# Generated by Django 5.1.1 on 2024-12-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_ordersummary_combo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Hand Over to Courier', 'Hand Over to Courier'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=25),
        ),
    ]
